version: '3'

services:
  php:
    container_name: setup-php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./demo:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - setup-network

  nginx:
    container_name: setup-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - '9020:80'
      - '9443:443'
    volumes:
      - ./demo:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - atende

  mysql:
    environment:
      MYSQL_HOST: 172.20.0.4
      MYSQL_DATABASE: contador
      MYSQL_USER: root
      MYSQL_PASSWORD: Ncm@647534

  phpmyadmin:
    container_name: setup-phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - '8888:80'
    networks:
      - atende
    environment:
      PMA_HOST: connect-mysql
    depends_on:
      - connect-mysql

  redis:
    container_name: setup-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - '6379:6379'

networks:
  atende:
    driver: bridge


volumes:
  setup-data:
    driver: local